<getopt.h> now explicitly included in bamcmp.cpp as versions getopt() has been moved in it's own file in the recent version.
FYI: Make process produced the following error:

error: 'getopt' was not declared in this scop

Now fixed.